version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: main
  reviewers:
  - t-ober
  - sensarmad
  - sebastian-peter
  - danielfeismann
  ignore:
    - dependency-name: org.scalatest:scalatest_2.13
      versions:
        - 3.3.0-SNAP+
    - dependency-name: org.scalatestplus:mockito-3-4_2.13
      versions:
        - 3.3.0.0-SNAP+